### ISSUE TITLE
iDeal payment

### ISSUE THREAD

**Issue by Fatihpk** [DamianMehers/XamarinStripe#3]
Hi Damian,

This SDK and sample is a great code thank you for that.
But I am searching now **for months** a sample with Xamarin Forms and iDeal Payment (Holland / Netherlands).

Do you have a sample code for the iDeal payment with Stripe?

Thanx

**Comment by DamianMehers** [comment]
I'm afraid I'm not familiar with iDeal ... I don't have sample code for it.

Damian

**Comment by Fatihpk** [comment]
Ok! Thats a shame! Searching for **months now** for this simple iDeal (very populair) payment system with Xamarin Forms.

Thank you anyway
